export const userData1 = [
{id_votes: 1, registro: '2024-09-29', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 2, registro: '2024-09-29', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 3, registro: '2024-09-29', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 4, registro: '2024-09-29', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 5, registro: '2024-09-29', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 6, registro: '2024-09-29', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 7, registro: '2024-09-29', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 8, registro: '2024-09-29', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 9, registro: '2024-09-29', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 10, registro: '2024-09-29', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 11, registro: '2024-09-29', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 12, registro: '2024-09-29', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 13, registro: '2024-09-29', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 14, registro: '2024-09-29', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 15, registro: '2024-09-29', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 16, registro: '2024-09-30', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 17, registro: '2024-09-30', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 18, registro: '2024-09-30', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 19, registro: '2024-09-30', restaurante: {id: 3, nome: 'Grill e Bem-Estar',descricao: 'Descrição'}      },
{id_votes: 20, registro: '2024-09-30', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 21, registro: '2024-09-30', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 22, registro: '2024-09-30', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 23, registro: '2024-09-30', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 24, registro: '2024-09-30', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 25, registro: '2024-09-30', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 27, registro: '2024-09-30', restaurante: {id: 3, nome: 'Grill e Bem-Estar',descricao: 'Descrição'}      },
{id_votes: 28, registro: '2024-09-30', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 29, registro: '2024-09-30', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 30, registro: '2024-09-30', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 31, registro: '2024-10-01', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 32, registro: '2024-10-01', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 33, registro: '2024-10-01', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 34, registro: '2024-10-01', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 35, registro: '2024-10-01', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 36, registro: '2024-10-01', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 37, registro: '2024-10-01', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 38, registro: '2024-10-01', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 39, registro: '2024-10-01', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 40, registro: '2024-10-01', restaurante: {id: 1, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 41, registro: '2024-10-01', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 42, registro: '2024-10-01', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 43, registro: '2024-10-01', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 44, registro: '2024-10-01', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 45, registro: '2024-10-01', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 46, registro: '2024-10-02', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 47, registro: '2024-10-02', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 48, registro: '2024-10-02', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 49, registro: '2024-10-02', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 50, registro: '2024-10-02', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 51, registro: '2024-10-02', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 52, registro: '2024-10-02', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 53, registro: '2024-10-02', restaurante: {id: 3, nome: 'Grill e Bem-Estar',descricao: 'Descrição'}      },
{id_votes: 54, registro: '2024-10-02', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 55, registro: '2024-10-02', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 56, registro: '2024-10-02', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 57, registro: '2024-10-02', restaurante: {id: 2, nome: 'Receita do Chefe',descricao: 'Descrição'}      },
{id_votes: 58, registro: '2024-10-02', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 59, registro: '2024-10-02', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 60, registro: '2024-10-02', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 61, registro: '2024-10-03', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 62, registro: '2024-10-03', restaurante: {id: 1, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 63, registro: '2024-10-03', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 64, registro: '2024-10-03', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 65, registro: '2024-10-03', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 66, registro: '2024-10-03', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 67, registro: '2024-10-03', restaurante: {id: 3, nome: 'Grill e Bem-Estar',descricao: 'Descrição'}      },
{id_votes: 68, registro: '2024-10-03', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 69, registro: '2024-10-03', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 70, registro: '2024-10-03', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 71, registro: '2024-10-03', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 72, registro: '2024-10-03', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 73, registro: '2024-10-03', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 74, registro: '2024-10-03', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 75, registro: '2024-10-03', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 76, registro: '2024-10-04', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 77, registro: '2024-10-04', restaurante: {id: 1, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 78, registro: '2024-10-04', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 79, registro: '2024-10-04', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 80, registro: '2024-10-04', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 81, registro: '2024-10-04', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 82, registro: '2024-10-04', restaurante: {id: 2, nome: 'Receita do Chefe',descricao: 'Descrição'}      },
{id_votes: 83, registro: '2024-10-04', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 84, registro: '2024-10-04', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 85, registro: '2024-10-04', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 86, registro: '2024-10-04', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 87, registro: '2024-10-04', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 88, registro: '2024-10-04', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 89, registro: '2024-10-04', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 90, registro: '2024-10-04', restaurante: {id: 3, nome: 'Grill e Bem-Estar', descricao: 'Descrição'}      },
{id_votes: 91, registro: '2024-10-05', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 92, registro: '2024-10-05', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 93, registro: '2024-10-05', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 94, registro: '2024-10-05', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 95, registro: '2024-10-05', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 96, registro: '2024-10-05', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 97, registro: '2024-10-05', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 98, registro: '2024-10-05', restaurante: {id: 1, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 99, registro: '2024-10-05', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 100, registro: '2024-10-05', restaurante: {id: 1, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 101, registro: '2024-10-05', restaurante: {id: 1, nome: 'Moda da Casa', descricao: 'Descrição'}      },
{id_votes: 102, registro: '2024-10-05', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },
{id_votes: 103, registro: '2024-10-05', restaurante: {id: 2, nome: 'Receita do Chefe', descricao: 'Descrição'}      },
{id_votes: 104, registro: '2024-10-05', restaurante: {id: 1, nome: 'Moda da Casa',descricao: 'Descrição'}      },
{id_votes: 105, registro: '2024-10-05', restaurante: {id: 4, nome: 'De Bem com a Vida', descricao: 'Descrição'}      },

];
      